syms x y z;
f=sqrt(x^2+y^2)-z;
fx=diff(f,x);
fy=diff(f,y);
x=1;
y=1;
z=sqrt(2);
fxv=eval(fx);
fyv=eval(fy);
[x,y]=meshgrid(-2:0.1:2);
z1=abs(sqrt(x.^2+y.^2));
z2=fxv*(x-1)+fyv*(y-1)+sqrt(2);
t=-1:0.1:1;
x3=fxv*t+1;
y3=fyv*t+1;
z3=-t+sqrt(2);
figure;
title('第1题图');
hold on;
mesh(x,y,z1);
mesh(x,y,z2);
plot3(x3,y3,z3);
axis equal;
hold off;

x1=linspace(-2,2);
y1=linspace(-2,2);
[x,y]=meshgrid(x1,y1);
u=x.*x+y.*y;
v=2.*x.*y;
figure;
mesh(x,y,u);
title('第2题u(x,y)的图像');
figure;
mesh(x,y,v);
title('第2题v(x,y)的图像');
figure;
h1=contour(x,y,u,'ShowText','on');
title('第2题u(x,y)的等高线');
figure;
h2=contour(x,y,v,'ShowText','on');
title('第2题v(x,y)的等高线');

x1=linspace(-2,2);
y1=linspace(-2,2);
[x,y]=meshgrid(x1,y1);
f=x.^4-8.*x.*y+2.*y.*y-3;
figure;
h=contour(x,y,f,'ShowText','on');
title('第3题f(x,y)的等高线');
syms x y;
f=x.^4-8.*x.*y+2.*y.*y-3;
eqn=[diff(f,x)==0,diff(f,y)==0];
vars=[x,y];
s=solve(eqn,vars);
v1=double(subs(f,vars,[s.x(1),s.y(1)]));
v2=double(subs(f,vars,[s.x(2),s.y(2)]));
v3=double(subs(f,vars,[s.x(3),s.y(3)]));
vmax=max(max(v1,v2),v3);
vmin=min(min(v1,v2),v3);
